<?php
$typeArr[1] = '关于我们';
$typeArr[2] = '公司简介';
$typeArr[3] = '组织架构';
$typeArr[4] = '发展历程';
$typeArr[5] = '旗下品牌';
$typeArr[6] = '致青春';
$typeArr[7] = '动漫风';
$typeArr[8] = '世界风';
$typeArr[9] = '东方·会';
$typeArr[10] = '新闻资讯';
$typeArr[11] = '品牌新闻';
$typeArr[12] = '行业资讯';
$typeArr[13] = '媒体报道';
$typeArr[14] = '会员中心';
$typeArr[15] = '会员卡分类';
$typeArr[16] = '会员权益';
$typeArr[17] = '会员俱乐部';
$typeArr[18] = '精彩专题';
$typeArr[19] = '加盟合作';
$typeArr[20] = '加盟优势';
$typeArr[21] = '加盟支持';
$typeArr[22] = '加盟条件';
$typeArr[23] = '加盟费用';
$typeArr[24] = '联系我们';
$typeArr[25] = '联系我们';
$typeArr[26] = '在线留言';
?>