<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,363);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",403,454);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3050,3085);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",3164,3190);
$z[5][4]['name']="image";
$z[6]=Array("field","",3270,3289);
$z[6][4]['name']="title";
$z[7]=Array("field","",3573,3591);
$z[7][4]['name']="body";
$z[8]=Array("productimagelist","\r\n                <li>\r\n                  <div><img src=\"[field:imgsrc/]\" url='javascript:void(0);' text=\"\" bigImg=\"[field:imgsrc/]\" alt=\"\"></div>\r\n                </li>\r\n                ",4588,4822);
$z[9]=Array("arclist","\r\n        <li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n        ",5073,5208);
$z[9][4]['typeid']="18";
$z[9][4]['titlelen']="60";
$z[9][4]['row']="10";
$z[10]=Array("include","",5458,5495);
$z[10][4]['filename']="footer.htm";

?>