<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,363);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",403,454);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3048,3083);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n        ",3232,3450);
$z[5][4]['type']="son";
$z[5][4]['currentstyle']="<li><a href='~typelink~' class='left_current'>~typename~</a></li>";
$z[6]=Array("field","",3636,3665);
$z[6][4]['name']="typename";
$z[7]=Array("field","",3862,3881);
$z[7][4]['name']="title";
$z[8]=Array("field","",3963,3983);
$z[8][4]['name']="source";
$z[9]=Array("adminname","",4005,4022);
$z[10]=Array("field","",4043,4095);
$z[10][4]['name']="pubdate";
$z[10][4]['function']="MyDate('Y-m-d',@me)";
$z[11]=Array("field","",4164,4182);
$z[11][4]['name']="body";
$z[12]=Array("prenext","",4456,4481);
$z[12][4]['get']="pre";
$z[13]=Array("prenext","",4508,4534);
$z[13][4]['get']="next";
$z[14]=Array("include","",4678,4715);
$z[14][4]['filename']="footer.htm";

?>