<li> <a href="[field:arcurl/]" title="[field:title/]" class="special_img"><img src="[field:picname/]"></a>
      <div class="special_div">
        <h3><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h3>
        <p>[field:description function='cn_substr(@me,500)'/]...</p>
        <div class="bottom"> <font>浏览量：[field:click/]</font> <a href="[field:arcurl/]">更多详细>></a> </div>
      </div>
    </li>