<?php
$z[0]=Array("global","",216,243);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",316,343);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",346,372);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("channel","\r\n      <li><a href=\"[field:typeurl/]\" >[field:typename/]</a></li>\r\n      ",1062,1294);
$z[3][4]['type']="top";
$z[3][4]['row']="10";
$z[3][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";

?>